[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solsafe_program = "FfV3AHU6WS7aPz53DnVvWBMEZR46ydGkEtKpLiKfRTrR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = 'C:\\Users\\HP SPECTRE X360 13\\.config\\solana\\id.json'

[scripts]
test = "ts-mocha -t 1000000 tests/**/*.ts"
