[toolchain]
anchor_version = "0.30.1"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
solsafe_program = "ELuQ38SztUfu7vBaR9P2sHEtSFTZkU1UDvTouoWfnQC3"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "ts-mocha -t 1000000 tests/**/*.ts"
