[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
solsafe_program = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "ts-mocha -t 1000000 tests/**/*.ts"